<?php

namespace Batyukovstudio\LaravelStaticImage;

use Batyukovstudio\LaravelStaticImage\Containers\StaticImageSection\StaticImage\Providers\MainServiceProvider;
use Illuminate\Support\ServiceProvider;

class LaravelStaticImageServiceProvider extends ServiceProvider
{


    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->app->register(MainServiceProvider::class);

    }

    public function boot()
    {
        $this->publishes([
            __DIR__ . '/Containers/StaticImageSection/StaticImage/Config/staticImageSection-staticImage.php' => config_path('laravel-static-image.php'),
            __DIR__ . '/resources/components/image.blade.php' => resource_path('components/image.blade.php')
        ], 'laravel-static-image');

        $this->mergeConfigFrom(__DIR__ . '/Containers/StaticImageSection/StaticImage/Config/staticImageSection-staticImage.php','laravel-static-image');

    }

}