<?php

namespace Batyukovstudio\LaravelStaticImage;

use Batyukovstudio\LaravelStaticImage\Containers\StaticImageSection\StaticImage\Providers\MainServiceProvider;
use Batyukovstudio\LaravelStaticImage\Containers\StaticImageSection\StaticImage\UI\CLI\DeleteConversionsCommand;
use Batyukovstudio\LaravelStaticImage\Containers\StaticImageSection\StaticImage\UI\CLI\GenerateConversionsCommand;
use Illuminate\Support\ServiceProvider;

class LaravelStaticImageServiceProvider extends ServiceProvider
{


    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->app->register(MainServiceProvider::class);

    }

    public function boot()
    {
        $this->publishes([
            __DIR__ . '/Containers/StaticImageSection/StaticImage/Config/staticImageSection-staticImage.php' => config_path('laravel-static-image.php'),
            __DIR__ . '/resources/components/static-image.blade.php' => resource_path('components/image.blade.php'),
            __DIR__ . '/../conversion-config.json' => base_path('conversion-config.json'),

        ], 'laravel-static-image');

        $this->mergeConfigFrom(__DIR__ . '/Containers/StaticImageSection/StaticImage/Config/staticImageSection-staticImage.php', 'laravel-static-image');

        if ($this->app->runningInConsole()) {
            $this->commands([
                GenerateConversionsCommand::class,
                DeleteConversionsCommand::class,
            ]);
        }
    }

}